<option >{{__("Select")}}</option>
<option value="Red">Red</option>
<option value="Orange">Orange</option>
<option value="Yellow">Yellow</option>
<option value="Green">Green</option>
<option value="Blue">Blue</option>
<option value="Purple">Purple</option>
<option value="Pink">Pink</option>
<option value="White">White</option>
<option value="Gray">Gray</option>
<option value="Brown">Brown</option>
<option value="Black">Black</option>
